nome=input("Nome do funcionário: ")
empresa=input('Nome da empresa: ')
qtdDeFuncionários=int(input('Quantidade de funcionários: '))
media_mensalidade=float(input("O salário: "))
print(nome + " trabalha na empresa ", empresa)
print('Possui: ', qtdDeFuncionários, " funcionários.")
print("A média da mensalidade é de: " + str(media_mensalidade))
print("O tipo de dado da variável [nome] é ", type(nome))
print("O tipo de dado da variável [empresa] é ", type(empresa))
print("O tipo de dado da variável [qtdDeFuncionários] é ", type(qtdDeFuncionários))
print("O tipo de dado da variável [media_mensalidade] é ", type(media_mensalidade))